# Generated by Django 3.1.1 on 2020-09-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200929_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
    ]
